name: Build

on: [pull_request, push]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: sudo apt install -y build-essential cmake
      - name: cmake
        run: cmake -DUSE_CLANG_TIDY=1 .
      - name: make
        run: make -j`nproc`
  build-on-macos:
    runs-on: macos-12
    steps:
       - uses: actions/checkout@v2
       - name: install build dependencies
         run: |
           brew install llvm
           ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"
           brew install cmake
       - name: cmake
         run: cmake -DUSE_CLANG_TIDY=1 .
       - name: make
         run: make -j`nproc`
  build-on-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: '14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44'
      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'msbuild-vcpkg'
          buildPreset: 'msbuild-vcpkg'
